### ISSUE TITLE
Missing class path and improvement to the README.md

### ISSUE THREAD

**Issue by johan-alexandersson** [Martoni/GbHdmi#1]
I suspect I'm doing many things wrong here but seems I'm getting stuck with the current build documentation. First time I'm getting familiar with Chisel and FPGA's over all, so this is a learning experience for me. So if I'm doing something horribly wrong here, let me know. :)

I've installed `sbt 1.4.9` through `brew` on a MacOS system, see versions in [sbt_evicted_paste.txt](https://github.com/Martoni/GbHdmi/files/7489924/sbt_evicted_paste.txt)

1. It seems for [GbVga](https://github.com/Martoni/GbVga) the dependencies docs, maybe the commands should be the following?
```
$ git clone https://github.com/Martoni/GbVga.git
$ cd GbVga/chisel/
$ sbt publishLocal
```
If I do publishLocal on the root of the repository GbHdmi can not find the dependency. Doing in the `chisel` directory seem to make dependencies for GbHdmi work.

2. I'm running into `Symbol is missing from classpath` errors when trying to run `sbt "runMain gbhdmi.TobGbHdmiDriver"`. Been trying my best to figure out what is going wrong but can't quite figure it out. Maybe it has something to do with my solution to prior issues? Console output attached. [console_paste.txt](https://github.com/Martoni/GbHdmi/files/7489904/console_paste.txt)

Feel free to disregard if I'm doing something horribly wrong in the build process. Maybe aid me in my fault search? But this project has inspired me to take another look at the rather intimidating FPGA space. :)

**Comment by Martoni** [comment]
Hi Johan,

1. Good remark for GbVga ! I'm fixing README.md
2. There is a typo mistake in your command, But I don't think it's the actual problem. In fact, I think, some of the dependency have been upgraded to Chisel 3.5 (HdmiCore, fpgamacro) and other no (GbVga, GbHdmi). I will update it.

**Comment by Martoni** [comment]
Should works now.

Tell me if it's ok.

**Comment by johan-alexandersson** [comment]
Yep! Pull down latest on both GbHdmi and GbVga and now everything builds just fine. Thank you!
