### ISSUE TITLE
How to connect the Game Boy controller pins

### ISSUE THREAD

**Issue by kiwanowski** [Martoni/GbHdmi#2]
in the gbhdmi.cst file you have:

IO_LOC "gbpad_a"      16;
IO_LOC "gbpad_b"      13;
IO_LOC "gbpad_select" 17;
IO_LOC "gbpad_start"  18;
IO_LOC "gbpad_right"  19;
IO_LOC "gbpad_left"   20;
IO_LOC "gbpad_up"     21;
IO_LOC "gbpad_down"   22;

and on the game boy you have pins - P10, P11, P12, P13, P14 and P15

how do you connect those?

**Comment by Martoni** [comment]
I have some electronic problem with this part for the moment.
But You can't connect gbpad_x directly to Pxx pin. An electronic wiring with opto-isolator and diodes is required.
I'm doing some more test before publishing the schematic

**Comment by Martoni** [comment]
![gbkeypad_wiring_bugged](https://github.com/Martoni/GbHdmi/blob/main/images/gbkeypad_wiring_bugged.png)

I have a problem with this wiring. I can't press two buttons on same "line" (B and left, A and right, ...). 

If you have some idea to fix it ?

**Comment by kiwanowski** [comment]
![gbkeypad_wiring_bugged](https://user-images.githubusercontent.com/10254780/154644650-8ed77e0d-127c-4f61-8dec-f38b238f0046.png)

Maybe something like this? The GPIOs would have to be pulled up and go low when the button is pressed

**Comment by kiwanowski** [comment]
![gbkeypad_wiring_bugged](https://user-images.githubusercontent.com/10254780/154647317-1088d541-85df-4e40-b668-9bbc871e4d4d.png)

Another idea

**Comment by Martoni** [comment]
Yes I tryied with this last schematic with a shottky diode RSX101M-30.
But button remain "exclusive" with it. Maybe my wiring hack is bad, or wrong diode.

**Comment by Martoni** [comment]
I think the LTV-247 is not strong enough to maintain two buttons pressed together. I will try with lighter resistor (47 Ohms instead of 4.7k) then with a dartlington opto-isolator.

**Comment by kiwanowski** [comment]
Cant you just implement the optoisolator logic inside the tang nano? Examples:
https://github.com/andy-west/consolized-game-boy/blob/main/src/nes-controller-gb/nes-controller-gb.c
https://gist.github.com/uXeBoy/5e9ec52823b7d73a187370573bdbda1b

**Comment by Martoni** [comment]
Thanks @kiwanowski, I hadn't found out how the keypad works at the time I made this electronic board.
I'll try it and patch my circuit.

**Comment by Martoni** [comment]
@kiwanowski it's works \o/ with commit https://github.com/Martoni/GbHdmi/commit/5cbc4296c20e8f9961657b98b5afe207238ce324

I «drived» P14 and P15 with 47k pull-up resistor (on 1.8V) and drived P10,11,12,13 directly with 5V buffers.

I will modify my kicad schematics and publish it.

**Comment by kiwanowski** [comment]
Do you have a pdf schematic of the board to share?

**Comment by Martoni** [comment]
> Do you have a pdf schematic of the board to share?

I'm upgrading new schematics version.

But I tested modification with this schematics modifications :


![gbhdmi_hack](https://user-images.githubusercontent.com/789580/165371327-b30e0e39-366f-4ecf-99ce-4b85628e863e.jpg)

**Comment by kiwanowski** [comment]
Thanks
